### ISSUE TITLE
MissingMethodException: Method not found: 'Void Sentry.HubExtensions.AddBreadcrumb(Sentry.IHub, System.S

### ISSUE THREAD

**Issue by insanity13** [getsentry/sentry-dotnet-ef#11]
###Environment
**How do you use Sentry?**
Sentry SaaS

**Which SDK and version?**
e.g: Sentry 3.0.3, Sentry Protocol 2.1.8, Sentry Abstractions 1.1.1, EF 6.4.4

### Steps to Reproduce

            // Set up the sentry SDK
            _sentry = SentrySdk.Init(o =>
            {
                o.Dsn = ConfigurationManager.AppSettings["SentryDsn"];
                o.Environment = "Production";
                o.Release = Common.Utils.SallsaUtils.GetBuildVersion();
                o.AttachStacktrace = true;
                o.ReportAssemblies = false;
                o.TracesSampleRate = 1;

                // Get Entity Framework integration
                //o.AddEntityFramework();
            });

### Actual Result

> MissingMethodException: Method not found: 'Void Sentry.HubExtensions.AddBreadcrumb(Sentry.IHub, System.String, System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, Sentry.Protocol.BreadcrumbLevel)'.

**Comment by bruno-garcia** [comment]
Updated: https://www.nuget.org/packages/Sentry.EntityFramework/3.0.3
