### ISSUE TITLE
MethodAccessException thrown when AddEntityFramework is called

### ISSUE THREAD

**Issue by mungk** [getsentry/sentry-dotnet-ef#4]
I'm following the example pretty closely. My code looks like this:

```
SentryDatabaseLogging.UseBreadcrumbs();

// Set up the sentry SDK
_sentrySdk = SentrySdk.Init(o =>
{
	// We store the DSN inside Web.config; make sure to use your own DSN!
	o.Dsn = new Dsn(ConfigurationManager.AppSettings["SentryDsn"]);

	// Add the EntityFramework integration
	o.AddEntityFramework();
});
```

However, when the AddEntityFramework method is actually executed as the site is initializing, it throws the following exception:

> System.MethodAccessException: Attempt by method 'Sentry.SentryOptionsExtensions.AddEntityFramework(Sentry.SentryOptions)' to access method 'Sentry.SentryOptionsExtensions.AddExceptionProcessor(Sentry.SentryOptions, Sentry.Extensibility.ISentryEventExceptionProcessor)' failed.

Visual Studio doesn't detect any issues in the editor or when it's compiled. It only occurs on execution. My only thought is that the [SentryOptionsExtensions.AddExceptionProcessor](https://github.com/getsentry/sentry-dotnet/blob/d08d8d47ea649db85cc26e38e12b4a2416ce866a/src/Sentry/SentryOptionsExtensions.cs#L56) is defined as internal and that is preventing the call from being successful at runtime.

Thoughts?

Thanks!
Andy

**Comment by bruno-garcia** [comment]
Which version of the `Sentry` package are you using?
That method was made internal on later versions of the `Sentry` package. 
The `Sentry.EntityFramework` package was still not made compatible with that.

As we can see on NuGet.org:

![image](https://user-images.githubusercontent.com/1633368/46574141-5baf5380-c99f-11e8-939a-d0a816746784.png)

The latest version of `Sentry.EntityFramework` still depends on `Sentry` version preview4.
Soon we'll be publishing a new version of this package depending on the version 1.0.0 of `Sentry` that was released last week

**Comment by mungk** [comment]
Yes, I'm using version 1.0.0 of the Sentry package. The dependency is marked as ">=" so I was just following that.  

Looking forward to the updated package. Do you have an ETA? Perhaps the dependency should be corrected if the update isn't imminent.

**Comment by bruno-garcia** [comment]
@mungk This is not a high priority ATM but we'd be happy to merge a PR.

All it's needed is updating ,in this repository, the dependency `Sentry` to 1.0.0 and getting it to build, run tests and run the sample to make sure things work as you expect.

After that I can publish the package.

**Comment by mungk** [comment]
@bruno-garcia Unfortunately, upgrading the ```Sentry``` dependency to 1.0.0 breaks this ```Sentry.EntityFramework``` package because that ```AddExceptionProcessor``` method was changed to internal instead of public. I'm not sure whether it should be:

1. Changed back to public, or:
2. ```Sentry.EntityFramework``` should be added to the ```Sentry``` ```InternalsVisibleTo``` list

Choice 1 seems reasonable to me, but I don't claim to know the ```Sentry``` package well enough to know why it was made internal.

Choice 2 seems like a burden moving forward as more and more extensions are added because they'll each need to be included on the list.

Either way, it's a change to the ```Sentry``` package itself and (depending on the option chosen) it may be an additional change to this ```Sentry.EntityFramework``` package as well.

**Comment by bruno-garcia** [comment]
You are right. I'm leaning towards making them public again although that is not part of the unified API of the Sentry SDKs. 
In any case, .NET is the only SDK which has a single hub since we can rely on `AsyncLocal`.

If you'd like to PR making those methods again public, I'd be happy to merge it in.

**Comment by bruno-garcia** [comment]
@mungk We still need to release a new version of `Sentry` package so this one can be updated and released. Ideally we'd combine with a couple more things before we make a release though.
/cc @xt0rted

**Comment by xt0rted** [comment]
The only build error I'm seeing right now is due to `AddExceptionProcessor()`. Once the new version of `Sentry` goes out this should be a pretty straight forward update.

**Comment by kanadaj** [comment]
Here is a temporary fix til it's public:
```
public static SentryOptions AddEntityFramework(this SentryOptions sentryOptions)
{
    var extensions = typeof(SentryOptionsExtensions);
    var addExceptionProcessorInfo = extensions.GetMethod("AddExceptionProcessor", BindingFlags.Static | BindingFlags.NonPublic);
    addExceptionProcessorInfo.Invoke(null, new object[]{ sentryOptions, new DbEntityValidationExceptionProcessor() });
    return sentryOptions;
}
```

Also, make sure to change the namespace of the file to Sentry.EntityFramework to avoid namespace collisions

**Comment by bruno-garcia** [comment]
Version [1.0.0](https://www.nuget.org/packages/Sentry.EntityFramework/1.0.0) was released.
Feel free to reopen if this issue persists.
